### ISSUE TITLE
General discussion about the layout, design, content, etc

### ISSUE THREAD

**Issue by therealmrmuffin** [raivo-otp/marketing-website#1]
Original issue: https://github.com/raivo-otp/ios-application/issues/106

**Comment by therealmrmuffin** [comment]
@tijme the donation regarding the website's domain has been made.

**Comment by tijme** [comment]
Thanks again @therealmrmuffin! 🔥 

I'll keep this issue open until the marketing website is used in production. Although it is already online, it also has to go through the review process of Apple once. If that's done, I'll close this general discussion.

**Comment by therealmrmuffin** [comment]
@tijme i recommend you to do the following for DNS in cloudflare to add additional security to raivo's website.

Adding a SPF record with no IP's or domains in it to prevent phishing and spoofing.
text in whatever TTL / @ / v=spf1 -all

Same with a DKIM record.
text in whatever TTL / _domainkey.raivo-otp.com / v=DKIM1; p=

And then DMARC as well.
txt in whatever TTL / _dmarc.raivo-otp.com / v=DMARC1; p=reject; sp=reject; adkim=s; aspf=s;

And then a CAA to restrict SSL Certificate issuing.
caa in whatever TTL / @ / 0 issue "letsencrypt.org"

And the also maybe disabling the proxying of cloudflare to stop cloudfare from collecting analytics on your users and maybe even adding the same SPF record and DKIM record to all of your subdomains as well. To prevent phishing and spoofing on the subs as well.

Ps, if you have removed the verification records from github in cloudflare's DNS then i would re-add them if i were you, to prevent the domain and stuff from getting unverified on github in the future.

**Comment by tijme** [comment]
Added most of it. Quick question, doesn't the DKIM record need a selector? Furthermore, I don't send mail myself using the domain, so would DKIM really increase security?

**Comment by therealmrmuffin** [comment]
DKIM doesn't not no. It also works without a key. And yes, it would also classify all emails being send from the domain as having the DKIM check being failed.

**Comment by therealmrmuffin** [comment]
@tijme btw make sure to setup that HTTPS redirect in the pages setting.

**Comment by tijme** [comment]
Fixed. I used the redirect in CloudFlare at first, but as the DNS proxy is now disabled I had to re-enable the redirect in GitHub.

**Comment by tijme** [comment]
Closing this as the website is now in production 👌
