### ISSUE TITLE
"How do I restore from a ZIP-archive export?" FAQ Incorrect

### ISSUE THREAD

**Issue by Arvind-Srinivasan** [raivo-otp/marketing-website#17]
The last [FAQ](https://raivo-otp.com/faq/) states:

> Unfortunately Raivo OTP does not currently support restoring from your ZIP-archive export. This is an [open feature request](https://github.com/raivo-otp/ios-application/issues/22) tracked on GitHub. As an alternative way to restore from your ZIP-archive export, you can scan each QR-code in the HTML file of your ZIP-archive export manually.

However, checking the [issue](https://github.com/raivo-otp/ios-application/issues/22) shows the problem is actually fixed! Thus, updating the website to avoid confusion would be great.

**Comment by tijme** [comment]
Thanks for reporting!
