### ISSUE TITLE
Link the domain of the website to the raivo-otp github organization.

### ISSUE THREAD

**Issue by therealmrmuffin** [raivo-otp/marketing-website#3]
Like the title says, i would like for the domain (raivo-otp.com) to be linked to the raivo-otp github organization.

**Comment by tijme** [comment]
What do you mean exactly by linking? Just putting the link in the organisation profile?

**Comment by therealmrmuffin** [comment]
Yes and no. I mean, more like verifying the domain via DNS and getting it added as a verified domain on the organization profile?

**Comment by tijme** [comment]
Fixed 💪
