### ISSUE TITLE
Migrate Freshdesk to marketing website

### ISSUE THREAD

**Issue by tijme** [raivo-otp/marketing-website#4]

**Comment by therealmrmuffin** [comment]
@tijme Maybe MKDocs can replace your freshdesk support website: https://www.mkdocs.org/user-guide/deploying-your-docs/

**Comment by tijme** [comment]
I've added an FAQ + support section to the website. Hopefully it's sufficient for Apple.

**Comment by cjerrington** [comment]
There is also: [Just the Docs](https://just-the-docs.github.io/just-the-docs/)

Another Jekyll Github pages friendly docs.

**Comment by tijme** [comment]
Thanks for the suggestions. I've migrated the FAQ/support page to the marketing website and Apple approved it. I've scheduled Raivo's Freshdesk to be deleted at the end of the month.
